apiVersion: v1
kind: Service
metadata:
  name: {{ .ServiceName }}-output
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30010
    targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
